name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the version of Python that matches your Lambda runtime

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas python-dateutil -t .

      - name: Package Lambda function
        run: |
          zip -r my_lambda_function.zip .

      - name: Upload Lambda function to AWS
        uses: aws-actions/aws-lambda-update-function-code@v1
        with:
          function-name: csvsplitter
          zip-file: my_lambda_function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: your-region  # e.g., 'us-east-1'

      - name: Clean up
        run: |
          rm my_lambda_function.zip
